---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.5.27
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:rainman4007/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: artifactory.corp.creditkarma.com/tax/memcache
      tag: 1.5.27-1575657408-83711052860d
    replicaCount: 3
