---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:1.5.27-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:rainman4007/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: artifactory.corp.creditkarma.com/tax/memcache
      tag: 1.5.27-1575657408-83711052860d
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
